GSM-MSG/SMS-DevOps

- .github/workflows/discodbot-cd.yml
- appspec.yml
- scripts/server_start.sh
- scripts/server_stop.sh
Discord Bot CD 파이프라인 구축
- ec2 생성
- codedeploy 사용해서 배포
- codedeploy 사용 => appspec, sciprts  들 작성
- 테라폼 유지보수는 추후 진행할 예정입니다.
> Discord Bot CD 파이프라인 구축

- .github/workflows/fitcloud-fee-bot.yml
주기 2분으로 변경
정상 작동 테스트를 위해 실행 주기를 2분으로 변경했습니다
> 🚑  주기 2분으로 변경

- automation/discord-bot/CD/android_bot.py
:recycle: :: 코드 리펙토링 및 커맨드 위치 변경
- 테스트를 위해 1커밋만 하고 메인에 머지합니다.
> :recycle: :: 코드 리펙토링 및 커맨드 위치 변경

- .github/workflows/discodbot-cd.yml
:pencil2: :: env -> ap-northeast-2 로 리전 변경
> :pencil2: :: env -> ap-northeast-2 로 리전 변경

- automation/discord-bot/CD/android_bot.py
> :recycle: :: 라이브러리 정리

- .github/workflows/fitcloud-fee-bot.yml
git action ubuntu 환경에 .env 파일 생성
파이썬 스크립트 실행에 필요한 .env파일 생성
> ✨  :: create .env file

- .github/workflows/fitcloud-fee-bot.yml
파이썬 버전 값을 문자열로 바꿈
- 파이썬 버전이 숫자로 인식되어서 값을 3.10에서 '3.10' 으로 바꾸었음
> :bug: :: 파이썬 버전이 3.10 버전이 3.1 버전으로 인식돼 값을 문자열로 바꿔줌

- .github/workflows/fitcloud-fee-bot.yml
git action cron 실행 주기 변경
- git action 정상작동 하는거 확인 후 주기를 원래대로인 한국 시 기준 오전 11시에 실행되도록 변경했습니다
> :recycle: :: 정상작동 확인 후 11시에 실행되게 변경

- .github/workflows/fitcloud-fee-bot.yml
- automation/discord-bot/fee-bot/requirements.txt
- automation/discord-bot/fee-bot/webhook-fitcloud-crawl-data.py
라이브러리 변경
- 라이브러리 변경후 메세지를 기존 일반 텍스트에서 embed형식으로 보내도록 변경했습니다
> 🔀 : 메세지를 embed로 보내기위해 라이브러리를 discord.py로 변경했습니다.

- automation/discord-bot/fee-bot/requirements.txt
라이브러리 변경
설치할 라이브러리 잘못 설정했었어서 고침
> 🔀 : misconfig dependencies

- automation/discord-bot/fee-bot/requirements.txt
request 라이브러리 추가
request 라이브러리 추가
> :bug: request 라이브러리는 또 언제 지웠었지..

- .github/workflows/fitcloud-fee-bot.yml
git action cron 주기 변경
git action cron 주기 변경
> 🔀  테스트 확인후 주기 원래대로 변경

- automation/discord-bot/fee-bot/webhook-fitcloud-crawl-data.py
메세지 변경
- 환율에 제목2(##) 를 주던 것을 총 비용에 제목2를 주도록 변경했습니다.
> 🔀 : 메세지에서 현재 환율을 강조하던 것을 총 비용을 강조하도록 변경했습니다.

- .github/workflows/fitcloud-fee-bot.yml
- automation/discord-bot/fee-bot/webhook-fitcloud-crawl-data.py
git action cron 주기 변경
- git action cron이 주기보다 늦게 실행되는 부분을 감안해 11시쯤에 실행되도록 실행 시간을 10시반으로 설정했습니다.
> 🔀 : git action cron이 주기보다 늦게 실행되는 것을 감안해 실행시간 30분전으로 변경했습니다.

- automation/discord-bot/CD/nyopa_bot.py
안드로이드 피드백 들으면서 지속적으로 수정할 것 같아서 draft 모드로 올려두겠습니다.
>  🔀 :: android merge pr 올리기 기능

- terraform/.terraform.lock.hcl
- terraform/init.tf
- terraform/sms-codedeploy.tf
- terraform/sms-dynamodb.tf
- terraform/sms-ec2.tf
terraform 컴퓨팅 관련 소스 리펙토링 및 추가
- codedeploy, codedeploygroup Iac
- IAM등 import
- 현재 사용하고 있지 않는 ec2 주석처리
- 버전 :latest 로 업데이트 (1.5.5)
> 🔀 :: terraform 컴퓨팅 관련 소스 리펙토링 및 추가

- automation/discord-bot/CD/nyopa_bot.py
- ios CD 연동
- ios CD 연동을 하기 위해 형우가 설정한? 곳에 post requests를 날리는 식으로 로직을 구성하였습니다.
> 🔀 :: ios CD 연동

- terraform/sms-dynamodb.tf
terraform 요소들 리펙토링
이제 슬슬 aws로 옮겨야해서 이 김에 컴퓨팅 요소들 리펙토링 좀 하고 오류나는거 수정하고, ec2 재구축하려고합니다.
> 🔀 :: terraform 요소들 리펙토링

- .github/workflows/terraform.yml
-lock=false 옵션 추가
기존 리소스들 때문에 -lock=false 옵션을 추가했습니다.
> 🔀  :: -lock=false 옵션 추가

- terraform/sms-ec2.tf
bastion 추가
workflow 덕에 테스트 Pr 좀 날리겠습니다.
> 🔀 :: bastion 추가

- terraform/sms-ec2.tf
> :poop: :: 테스트 용 커밋

- terraform/sms-vpc.tf
> :sparkles: :: nat 추가

- terraform/sms-vpc.tf
> :pencil2: :: 오타 수정

- terraform/sms-vpc.tf
> :sparkles: :: create eip

- terraform/sms-vpc.tf
> 🔀 :: 오타 수정

- automation/discord-bot/CD/Dockerfile
- terraform/sms-ecr.tf
nyopa 봇 관련 작업
도커 파일 작성, Ecr 테라폼 작성
이거 ecr 생성되는거 봐야돼서 머지하고 nyopa cd 수정한다음에 pr 한번 더 열게용
> 🔀 :: nyopa 관련 작업

- .github/workflows/discodbot-cd.yml
> 🔀  :: 뇨파 관련 CD 수정

- automation/discord-bot/CD/nohup.out
- automation/discord-bot/CD/nyopa_bot.py
모니터링 코드 다시 짤게요
모니터링 코드 다시 짤게요 (CD 돌릴려고 테스트 커밋임)
> 🔀 :: 모니터링 코드 다시 짤게요

- .github/workflows/discodbot-cd.yml
- automation/discord-bot/CD/nyopa_bot.py
경로 변경
CD 실패해서 경로 변경 해봤습니다.
안되면 추가적으로 조치 예정
> 🔀  :: 경로 변경

- .github/workflows/discodbot-cd.yml
- automation/discord-bot/CD/nyopa_bot.py
> :recycle: :: 경로 변경

- .github/workflows/discodbot-cd.yml
- automation/discord-bot/CD/nyopa_bot.py
> :poop: :: 테스트

- .github/workflows/discodbot-cd.yml
- automation/discord-bot/CD/nyopa_bot.py
> :recycle: :: checkout 안했음 ㅠ

- automation/discord-bot/CD/requirements.txt
> :memo: :: requirements 수정

- automation/discord-bot/CD/.gitignore
- terraform/sms-ecr.tf
ECR 생성 및 .gitignore 업데이트
- nginx ecr 생성
- .gitignore 업데이트
전용 nginx 사용하시는 것 같아서 Ecr 생성했습니다. 그냥 배포용 이미지? 사용하실거면 코멘트랑 남겨주시고 환경변수 세팅도 메인 서버에서 진행해주세요 🙏
> 🔀 :: ECR 생성 및 .gitignore 업데이트

- deploy/sms-backend/nginx/Dockerfile
- deploy/sms-backend/nginx/nginx-conf.txt
- terraform/sms-rds.tf
nginx Dockerfile
nginx Dockerfile
> 🔀  :: nginx Dockerfile

- automation/discord-bot/CD/requirements.txt
gh를 requirements에서 삭제
gh를 requirements에서 삭제
> 🔀 :: gh를 requirements에서 삭제

- automation/discord-bot/CD/nyopa_bot.py
> 🔀 :: 로직 변경

- automation/discord-bot/CD/nyopa_bot.py
> :bug: :: decode 삭제 및 문자열 정?리

- terraform/sms-ec2.tf
- terraform/sms-elb.tf
- terraform/sms-tg.tf
- elb 관련 작업 진행
- elb 생성
- tg 생성
- elb에 tg 연결해주기
- 혹시 모를 오타들 좀 잘봐주십쇼.
> 🔀 :: elb 관련 작업 진행

- terraform/sms-tg.tf
> :bug: :: 이름 변경

- terraform/sms-elb.tf
> :bug: :: for 문 고려안하고 코드 짬

- terraform/sms-elb.tf
> :bug: :: 버전 차이

- terraform/sms-elb.tf
> :bug: :: id 추가

- terraform/sms-elb.tf
- terraform/sms-tg.tf
> :recycle: :: 이슈 수정

- terraform/sms-tg.tf
> :recycle: :: 문법 이슈

- .github/workflows/discodbot-cd.yml
> 🔀  :: 오타정정

- automation/discord-bot/CD/nyopa_bot.py
> :poop :: CD 테스트

- automation/discord-bot/CD/Dockerfile
> 🔀  :: 권한 수정

- automation/discord-bot/CD/Dockerfile
> :poop: :: 원상복구

- automation/discord-bot/CD/Dockerfile
- automation/discord-bot/CD/nyopa_bot.py
nyopa 안드로이드쪽 업데이트
nyopa 안드로이드쪽 업데이트
> 🔀 :: nyopa 안드로이드쪽 업데이트

- .github/workflows/discodbot-cd.yml
- automation/discord-bot/log/load_cloudwatch_log.py
- automation/discord-bot/log/log_pagination_view.py
- automation/discord-bot/log/log_view.py
- automation/discord-bot/log/main_view.py
- automation/discord-bot/log/sunghun_bot.py
> 🔀 :: 성훈 봇 수정

- automation/discord-bot/log/Dockerfile
> 🔀  :: image 경량화

- automation/discord-bot/CD/nyopa_bot.py
- automation/discord-bot/log/load_cloudwatch_log.py
- automation/discord-bot/log/sunghun_bot.py
성훈봇 수정, 뇨파봇 일부 수정
ctx.message.channel을 사용해 성훈봇이 특정 채널에서만 작동하게끔 수정
PEP8을 준수하게끔 슬라이싱이 아닌 startswith함수를 사용
뇨파봇에서 ios채널 변수명과 동일하게 aos채널또한 channel에서 aos_channel로 변수명 변경
뇨파봇 변수 변경한거 확인해주세요
> 🔀 성훈봇 수정, 뇨파봇 일부 수정

- deploy/local-db/docker-compose.yml
테스트를 위해 로컬에 db를 띄우는 작업을 docker compose를 통해 자동화해두었습니다.
Resolves: #{074}
docker compose yml작성
local db 시작시 해야할 것들
- ./.env파일을 생성해 환경변수를 작성
- ./db/initdb.d/ 아래에 ddl.sql 작성
> 템플릿 체크리스트 말고도 추가적으로 필요한 체크리스트는 추가해주세요!
로컬에서 python 코드에서 테스트시 정상적으로 작동합니다.
> feat: local mysql구축을 자동화하였습니다.

- .github/workflows/instance_on_off.yml
- automation/pipeline_scripts/instance_on_off.py
> PR을 하게 된 문제상황, 배경 및 개요에 대해서 작성해주세요!
>
> 퍼블리싱의 경우 스크린샷/동영상도 추가해주면 좋아요!
Resolves: #{이슈번호}
> PR에서 한 작업을 작성해주세요!
> 구현 시에 고민이었던 점들 혹은 특정 부분에 대한 의도가 있었다면 PR 리뷰의 이해를 돕기 위해 서술해주세요!
>
> 또한 리뷰어에게 특정 부분에 대한 집중 혹은 코멘트 혹은 질문을 요청하는 경우에 작성하면 좋아요!
>
> e.g. 작업을 끝내야할 시간이 얼마 없어 확장성보다는 동작을 위주로 만들었어요! 감안하고 리뷰해주세요!
> 템플릿 체크리스트 말고도 추가적으로 필요한 체크리스트는 추가해주세요!
> aws credential 추가

- automation/discord-bot/fee-bot/webhook-fitcloud-crawl-data.py
fee cralwer가 작동을 안하길래
Resolves: #{이슈번호}
환율 api를 변경해줌
> 템플릿 체크리스트 말고도 추가적으로 필요한 체크리스트는 추가해주세요!
> 기존 환율 api가 사라져서 다른곳으로 변경해줌
